Repository Team-Frolog/Frolog_Web, pull requests merged in 2025-02, with the labels that each got.

#125 [Release]: safari z-index 이슈 해결
  src/__test__/components/Button/LinkButton.test.tsx
  src/__test__/components/Button/QuitButton.test.tsx
  src/__test__/components/Tap/Tap.test.tsx
  src/app/(user)/[userId]/well/[wellId]/book/[bookId]/(list)/layout.tsx
  src/app/(user)/[userId]/well/[wellId]/book/[bookId]/(list)/memo/page.tsx
  src/app/globals.css
  src/components/Header/DetailHeader.tsx
  src/components/Header/TabHeader.tsx
  src/components/Header/TapHeader.tsx
  src/components/Link/CustomLink.tsx
  src/components/Link/CustomMotionLink.tsx
  src/components/NavigationBar/NavItem.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/components/Tab/Tab.tsx
  src/components/Wrapper/HeaderWrapper.tsx
  src/constants/nav.ts
  src/constants/tabs.ts
  src/features/Book/components/BookDetail/BookInfoTap.tsx
  src/features/Book/components/ReviewsForBook/ReviewItem.tsx
  src/features/Book/hooks/useAddBookToWell.ts
  src/features/Feed/components/FeedList/FeedBar.tsx
  src/features/Feed/components/ProfileHeader.tsx
  src/features/Memo/hooks/useAddMemo.ts
  src/features/Memo/hooks/useMemoDetail.ts
  src/features/Profile/components/FollowList/FollowList.tsx
  src/features/Profile/components/HowToInstall/HowToInstall.tsx
  src/features/Profile/components/Profile/UserStatistics.tsx
  src/features/Profile/hooks/useProfileEdit.ts
  src/features/Review/components/MyReviewPage.tsx
  src/features/Review/components/ReviewList/ReviewList.tsx
  src/features/Review/hooks/useAddReview.ts
  src/features/Search/components/SearchInput.tsx
  src/features/Well/components/Well/Pointing/WellActionButton.tsx
  src/features/Well/components/Well/WellItem/WellItem.tsx
  src/features/Well/components/WellList/WellAddButton.tsx
  src/features/Well/components/WellList/WellIcon/WellIcon.tsx
  src/features/Well/hooks/useAddWellItem.ts
  src/hooks/gesture/useScroll.ts
  src/stories/components/Header/TabHeader.stories.tsx
  src/stories/components/Tab/Tab.stories.tsx
Labels: release

#126 [Release]: 피드 skeleton 버그 수정
  src/constants/category.ts
  src/constants/frogs.ts
  src/constants/jobs.ts
  src/constants/rating.ts
  src/constants/tabs.ts
  src/constants/tags.ts
  src/constants/theme.ts
  src/features/Feed/components/FeedList/FeedList.tsx
  src/features/Feed/components/Feeds.tsx
  src/features/Feed/hooks/feed/useFeed.ts
Labels: release

#128 [Feat/#120]: 우물 페이지 탭 구분, 검색창 및 우물 슬라이드 구현
  public/sw.js
  public/sw.js.map
  src/app/(default)/well-search/page.tsx
  src/app/(main)/(well)/explore/page.tsx
  src/app/(main)/(well)/layout.tsx
  src/app/(main)/(well)/page.tsx
  src/components/Header/TabHeader.tsx
  src/components/Header/TitleHeader.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/components/Slider/Slider.tsx
  src/components/Tag/TagSlider.tsx
  src/components/Wrapper/HeaderWrapper.tsx
  src/constants/images.ts
  src/constants/nav.ts
  src/constants/page.ts
  src/constants/tabs.ts
  src/features/Feed/components/ProfileHeader.tsx
  src/features/Memo/components/MemoForm/ImageForm/ImageSlider.tsx
  src/features/Profile/components/Profile/UserType.tsx
  src/features/Search/components/SearchHeader.tsx
  src/features/Search/components/SearchHome.tsx
  src/features/Search/components/SearchInput.tsx
  src/features/Well/components/WellList/SideWellHeader.tsx
  src/features/Well/components/WellSearch/WellSearchItem.tsx
  src/stories/features/Search/SearchMain.stories.tsx
  src/stories/features/Well/WellList/SideWellHeader.stories.tsx
  src/stories/features/Well/WellSearch/WellSearchItem.stories.tsx
Labels: feat

#129 [Feat/#120]: 우물 검색 기능 및 기타 수정
  src/app/(default)/well-search/page.tsx
  src/app/(main)/(well)/explore/page.tsx
  src/components/Fallback/Skeleton/FeedSkeleton.tsx
  src/components/Fallback/Skeleton/ProfileHeaderSkeleton.tsx
  src/components/Fallback/Skeleton/WellSearchItemSkeleton.tsx
  src/components/Header/ProfileHeader.tsx
  src/constants/theme.ts
  src/features/Book/components/ReviewsForBook/ReviewItem.tsx
  src/features/Feed/components/CommentList/ChildCommentItem.tsx
  src/features/Feed/components/CommentList/CommentItem.tsx
  src/features/Feed/components/FeedList/FeedItem.tsx
  src/features/Feed/index.ts
  src/features/Search/components/SearchInput.tsx
  src/features/Well/components/WellSearch/WellSearchItem.tsx
  src/features/Well/components/WellSearch/WellSearchResult.tsx
  src/features/Well/index.ts
  src/hooks/useProfile.ts
  src/providers/ThemeProvider.tsx
  src/stories/components/Header/ProfileHeader.stories.tsx
  src/styles/theme.css
Labels: refactor, feat

#130 [Refactor/#121]: api 리팩토링
  src/api/auth.api.ts
  src/features/Feed/api/comments.api.ts
  src/features/Join/api/join.api.ts
  src/features/Memo/api/memo.api.ts
  src/features/Profile/api/profile.api.ts
  src/features/ResetPassword/api/reset.api.ts
  src/features/Review/api/review.api.ts
  src/features/Search/api/register.api.ts
  src/features/Store/api/store.api.ts
  src/features/Well/api/well.api.ts
  src/features/Well/hooks/useRegisterStore.ts
Labels: refactor

#131 [Refactor/#116]: custom router, 동적 경로 생성 함수 적용
  src/__test__/components/Button/AddButton.test.tsx
  src/app/(default)/well-search/page.tsx
  src/app/(user)/[userId]/well/[wellId]/book/[bookId]/(list)/memo/page.tsx
  src/components/Book/BookInfo.tsx
  src/components/Button/AddButton.tsx
  src/components/Header/DetailHeader.tsx
  src/components/Header/ProfileHeader.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/features/Book/components/BookList/BookListItem.tsx
  src/features/Book/components/ReviewsForBook/ReviewItem.tsx
  src/features/Book/hooks/useAddBookToWell.ts
  src/features/Feed/components/FeedList/FeedBar.tsx
  src/features/Feed/components/FeedList/FeedContent.tsx
  src/features/Feed/components/FeedList/FeedItem.tsx
  src/features/Memo/components/MemoDetail.tsx
  src/features/Memo/components/MemoList/MemoListItem.tsx
  src/features/Memo/hooks/useAddMemo.ts
  src/features/Memo/hooks/useMemoDetail.ts
  src/features/Profile/components/FollowList/FollowItem.tsx
  src/features/Profile/components/Menu/MenuItem.tsx
  src/features/Profile/components/Profile/Profile.tsx
  src/features/Profile/components/Profile/UserStatistics.tsx
  src/features/Profile/components/Terms/TermsMenu.tsx
  src/features/Profile/hooks/useProfileEdit.ts
  src/features/Review/components/MyReviewPage.tsx
  src/features/Review/components/ReviewList/ReviewList.tsx
  src/features/Review/components/ReviewList/ReviewListItem.tsx
  src/features/Review/hooks/useAddReview.ts
  src/features/Review/hooks/useReviewDetail.ts
  src/features/Search/components/SearchInput.tsx
  src/features/Well/components/Well/Pointing/WellActionButton.tsx
  src/features/Well/components/Well/WellHeader.tsx
  src/features/Well/components/Well/WellItem/WellItem.tsx
  src/features/Well/components/WellList/WellAddButton.tsx
  src/features/Well/components/WellList/WellIcon/WellIcon.tsx
  src/features/Well/hooks/useAddWellItem.ts
  src/hooks/useCustomRouter.ts
  src/utils/getPath.ts
Labels: refactor

#133 [Refactor/#116]: 컴포넌트 분리, 상수 정리 등 리팩토링
  public/sw.js
  public/sw.js.map
  src/app/(user)/[userId]/well/[wellId]/book/[bookId]/(list)/layout.tsx
  src/app/(user)/[userId]/well/[wellId]/book/[bookId]/(list)/memo/page.tsx
  src/components/Button/AddButton.tsx
  src/components/Header/DetailHeader.tsx
  src/components/Header/FormHeader.tsx
  src/components/Header/ProfileHeader/ProfileHeader.tsx
  src/components/Header/ProfileHeader/ProfileImage.tsx
  src/components/Header/StoreHeader.tsx
  src/components/Header/TabHeader.tsx
  src/components/Link/CustomLink.tsx
  src/components/Link/CustomMotionLink.tsx
  src/components/NavigationBar/NavItem.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/components/Profile/FrologTestButton.tsx
  src/components/Tab/TabMenu.tsx
  src/components/Wrapper/HeaderWrapper.tsx
  src/constants/nav.ts
  src/constants/rating.ts
  src/constants/storage.ts
  src/constants/tabs.ts
  src/data/ui/bottomSheet.tsx
  src/features/Book/components/ReviewsForBook/ReviewItem.tsx
  src/features/Book/hooks/useAddBookToWell.ts
  src/features/Feed/components/CommentList/ChildCommentItem.tsx
  src/features/Feed/components/CommentList/CommentItem.tsx
  src/features/Feed/components/FeedList/FeedBar.tsx
  src/features/Feed/components/FeedList/FeedItem.tsx
  src/features/FrologTest/components/FrologTest.tsx
  src/features/FrologTest/components/ProgressHeader.tsx
  src/features/FrologTest/hooks/useTest.ts
  src/features/Join/components/JoinForm.tsx
  src/features/Join/hooks/useJoin.ts
  src/features/Login/hooks/useLogin.ts
  src/features/Memo/hooks/useAddMemo.ts
  src/features/Memo/hooks/useMemoDetail.ts
  src/features/Profile/hooks/useProfileEdit.ts
  src/features/ResetPassword/components/ResetPasswordForm.tsx
  src/features/ResetPassword/hooks/useResetPassword.ts
  src/features/Review/components/MyReviewPage.tsx
  src/features/Review/hooks/useAddReview.ts
  src/features/Review/hooks/useReviewDetail.ts
  src/features/Search/components/SearchInput.tsx
  src/features/Well/components/Well/Pointing/WellActionButton.tsx
  src/features/Well/components/Well/WellItem/WellItem.tsx
  src/features/Well/components/WellList/SideWellHeader.tsx
  src/features/Well/components/WellList/WellAddButton.tsx
  src/features/Well/components/WellList/WellIcon/WellIcon.tsx
  src/features/Well/components/WellSearch/WellSearchItem.tsx
  src/features/Well/hooks/useAddWellItem.ts
  src/hooks/gesture/useScroll.ts
  src/hooks/useCustomRouter.ts
  src/stories/components/Header/ProfileHeader.stories.tsx
  src/stories/components/Header/TabHeader.stories.tsx
  src/styles/variants/variants.ts
  src/types/nav.d.ts
  src/types/taps.d.ts
  src/utils/star.tsx
Labels: refactor

#134 [Feat/#120]: msw 세팅 및 useSearch hook 확장성 리팩토링
  next.config.js
  src/__mock__/apiMock.ts
  src/app/(main)/(well)/explore/page.tsx
  src/app/layout.tsx
  src/constants/query.ts
  src/features/Search/hooks/useSearchBook.ts
  src/features/Well/components/WellSearch/WellSearchItem.tsx
  src/features/Well/components/WellSearch/WellSearchResult.tsx
  src/hooks/useInfiniteSearch.ts
  src/providers/MSWProvider.tsx
  src/stories/features/Well/WellSearch/WellSearchItem.stories.tsx
Labels: refactor, setting

#135 [Feat/#116]: 스크롤 유지 기능 추가, UI 변경사항 반영
  package-lock.json
  package.json
  public/sw.js
  public/sw.js.map
  src/__test__/components/Button/AddButton.test.tsx
  src/components/Button/AddButton.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/components/Rating/RatingSelector.tsx
  src/constants/category.ts
  src/features/Book/components/AboutBook.tsx
  src/features/Book/components/BookDetail/BookInfoTap.tsx
  src/features/Book/components/BookList/BookListItem.tsx
  src/features/Book/components/ReviewsForBook/ReviewItem.tsx
  src/features/Book/components/ReviewsForBook/ReviewsForBook.tsx
  src/features/Feed/components/FeedList/FeedList.tsx
  src/features/Search/components/SearchResult.tsx
  src/features/Search/hooks/useSearch.ts
  src/features/Well/components/WellList/WellIcon/WellIcon.tsx
  src/hooks/gesture/useScrollPosition.ts
  src/store/userActionStore.ts
  src/stories/features/Book/ReviewsForBook/ReviewItem.stories.tsx
Labels: refactor, feat

#140 [Fix/#139]: 리뷰탭, 메모탭 이슈 수정
  src/components/Tab/TabMenu.tsx
  src/features/Review/components/ReviewList/ReviewList.tsx
  src/features/Review/hooks/useReviews.ts
Labels: fix

#144 [Setting]: ci 검사 main 브랜치 추가
  .github/workflows/ci.yml
Labels: setting

#146 [Fix/#145]: ci 수정 (chromatic)
  .github/workflows/ci.yml
Labels: fix
